export const USER_LOGGED_IN_KEY = 'LOGGED_IN';
export const USER_PASSED_WELCOME_SCREEN_KEY = 'PASSED_WELCOME_SCREEN';
export const USER_PASSED_ONBOARDING_KEY = 'PASSED_ONBOARDING';
export const USER_SESSION_KEY = 'SESSION';
