import { Image } from 'react-native';

import adultAvatar1 from '@/assets/images/adult-1.png';
import adultAvatar2 from '@/assets/images/adult-2.png';
import adultAvatar3 from '@/assets/images/adult-3.png';
import adultAvatar4 from '@/assets/images/adult-4.png';
import adultAvatar5 from '@/assets/images/adult-5.png';
import adultAccount from '@/assets/images/adult-account.png';
import bankAccount from '@/assets/images/bank_account.png';
import car from '@/assets/images/car.png';
import childAccount from '@/assets/images/child-account.png';
import college from '@/assets/images/college.png';
import connectingWallet1 from '@/assets/images/connecting-wallet-1.png';
import connectingWallet2 from '@/assets/images/connecting-wallet-2.png';
import dreams from '@/assets/images/dreams.png';
import adultAvatar from '@/assets/images/example-adult-avatar.png';
import childAvatar2 from '@/assets/images/example-child-avatar-2.png';
import childAvatar3 from '@/assets/images/example-child-avatar-3.jpg';
import childAvatar from '@/assets/images/example-child-avatar.png';
import familyCircle from '@/assets/images/family-circle.png';
import family from '@/assets/images/family.png';
import house from '@/assets/images/house.png';
import mail from '@/assets/images/mail.png';
import messages from '@/assets/images/messages.png';
import onboarding from '@/assets/images/onboarding.png';
import placeholder from '@/assets/images/placeholder-square.jpg';
import signal from '@/assets/images/signal.png';
import statisticsChart from '@/assets/images/statistics-chart.png';
import telegram from '@/assets/images/telegram.png';
import travel from '@/assets/images/travel.png';
import wechat from '@/assets/images/wechat.png';
import wedding from '@/assets/images/wedding.png';

export const onboardingImageUri = Image.resolveAssetSource(onboarding).uri;
export const adultAccountImageUri = Image.resolveAssetSource(adultAccount).uri;
export const childAccountImageUri = Image.resolveAssetSource(childAccount).uri;
export const adultAvatarImageUri = Image.resolveAssetSource(adultAvatar).uri;
export const adultAvatar1ImageUri = Image.resolveAssetSource(adultAvatar1).uri;
export const adultAvatar2ImageUri = Image.resolveAssetSource(adultAvatar2).uri;
export const adultAvatar3ImageUri = Image.resolveAssetSource(adultAvatar3).uri;
export const adultAvatar4ImageUri = Image.resolveAssetSource(adultAvatar4).uri;
export const adultAvatar5ImageUri = Image.resolveAssetSource(adultAvatar5).uri;
export const childAvatarImageUri = Image.resolveAssetSource(childAvatar).uri;
export const childAvatar2ImageUri = Image.resolveAssetSource(childAvatar2).uri;
export const childAvatar3ImageUri = Image.resolveAssetSource(childAvatar3).uri;
export const bankAccountImageUri = Image.resolveAssetSource(bankAccount).uri;
export const connectingWallet1ImageUri = Image.resolveAssetSource(connectingWallet1).uri;
export const connectingWallet2ImageUri = Image.resolveAssetSource(connectingWallet2).uri;
export const placeholderImageUri = Image.resolveAssetSource(placeholder).uri;
export const carImageUri = Image.resolveAssetSource(car).uri;
export const collegeImageUri = Image.resolveAssetSource(college).uri;
export const weddingImageUri = Image.resolveAssetSource(wedding).uri;
export const houseImageUri = Image.resolveAssetSource(house).uri;
export const dreamsImageUri = Image.resolveAssetSource(dreams).uri;
export const travelImageUri = Image.resolveAssetSource(travel).uri;
export const familyImageUri = Image.resolveAssetSource(family).uri;
export const messagesImageUri = Image.resolveAssetSource(messages).uri;
export const telegramImageUri = Image.resolveAssetSource(telegram).uri;
export const signalImageUri = Image.resolveAssetSource(signal).uri;
export const wechatImageUri = Image.resolveAssetSource(wechat).uri;
export const mailImageUri = Image.resolveAssetSource(mail).uri;
export const familyCircleImageUri = Image.resolveAssetSource(familyCircle).uri;
export const statisticsChartImageUri = Image.resolveAssetSource(statisticsChart).uri;
