# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    unless ENV["FASTLANE_USER"]
      UI.user_error!("FASTLANE_USER is not set. Create ios/fastlane/.env.default or export it before running.")
    end

    unless ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"]
      UI.user_error!("FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD is not set. Create ios/fastlane/.env.default or export it before running.")
    end

    # Ensure provisioning profiles are up to date and include Associated Domains
    match(type: "appstore", app_identifier: "com.silksoftwarehouse.blockydevs.nestifi", readonly: true)

    increment_version_number(bump_type: "patch")
    increment_build_number(xcodeproj: "NestiFiPrototype.xcodeproj")
    build_app(workspace: "NestiFiPrototype.xcworkspace", scheme: "NestiFiPrototype")
    upload_to_testflight
  end
end
